-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [securedrop_protocol_minimal]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import SecuredropProtocolMinimal.Extraction.Types
open Aeneas Aeneas.Std Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open securedrop_protocol_minimal

/-- [core::convert::{impl core::fmt::Debug for core::convert::Infallible}::fmt]:
    Source: '/rustc/library/core/src/convert/mod.rs', lines 942:4-942:60
    Name pattern: [core::convert::{core::fmt::Debug<core::convert::Infallible>}::fmt]
    Visibility: public -/
@[rust_fun "core::convert::{core::fmt::Debug<core::convert::Infallible>}::fmt"]
axiom core.convert.Infallible.Insts.CoreFmtDebug.fmt
  :
  core.convert.Infallible → core.fmt.Formatter → Result
    ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)

/-- [core::convert::{impl core::fmt::Display for core::convert::Infallible}::fmt]:
    Source: '/rustc/library/core/src/convert/mod.rs', lines 949:4-949:60
    Name pattern: [core::convert::{core::fmt::Display<core::convert::Infallible>}::fmt]
    Visibility: public -/
@[rust_fun
  "core::convert::{core::fmt::Display<core::convert::Infallible>}::fmt"]
axiom core.convert.Infallible.Insts.CoreFmtDisplay.fmt
  :
  core.convert.Infallible → core.fmt.Formatter → Result
    ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)

/-- [core::hint::must_use]:
    Source: '/rustc/library/core/src/hint.rs', lines 613:0-613:39
    Name pattern: [core::hint::must_use]
    Visibility: public -/
@[rust_fun "core::hint::must_use"]
axiom core.hint.must_use {T : Type} : T → Result T

/-- [core::result::{core::result::Result<T, E>}::map_err]:
    Source: '/rustc/library/core/src/result.rs', lines 962:4-964:53
    Name pattern: [core::result::{core::result::Result<@T, @E>}::map_err]
    Visibility: public -/
@[rust_fun "core::result::{core::result::Result<@T, @E>}::map_err"]
axiom core.result.Result.map_err
  {T : Type} {E : Type} {F : Type} {O : Type} (opsfunctionFnOnceOTupleEFInst :
  core.ops.function.FnOnce O E F) :
  core.result.Result T E → O → Result (core.result.Result T F)

/-- [alloc::fmt::format]:
    Source: '/rustc/library/alloc/src/fmt.rs', lines 649:0-649:52
    Name pattern: [alloc::fmt::format]
    Visibility: public -/
@[rust_fun "alloc::fmt::format"]
axiom alloc.fmt.format : core.fmt.Arguments → Result String

/-- [alloc::string::{impl core::fmt::Display for alloc::string::String}::fmt]:
    Source: '/rustc/library/alloc/src/string.rs', lines 2724:4-2724:60
    Name pattern: [alloc::string::{core::fmt::Display<alloc::string::String>}::fmt]
    Visibility: public -/
@[rust_fun "alloc::string::{core::fmt::Display<alloc::string::String>}::fmt"]
axiom alloc.string.String.Insts.CoreFmtDisplay.fmt
  :
  String → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- [alloc::string::{impl core::fmt::Debug for alloc::string::String}::fmt]:
    Source: '/rustc/library/alloc/src/string.rs', lines 2732:4-2732:60
    Name pattern: [alloc::string::{core::fmt::Debug<alloc::string::String>}::fmt]
    Visibility: public -/
@[rust_fun "alloc::string::{core::fmt::Debug<alloc::string::String>}::fmt"]
axiom alloc.string.String.Insts.CoreFmtDebug.fmt
  :
  String → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- [alloc::vec::{alloc::vec::Vec<T>}::as_slice]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 1854:4-1854:40
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::as_slice]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::as_slice"]
axiom alloc.vec.Vec.as_slice
  {T : Type} (A : Type) : alloc.vec.Vec T → Result (Slice T)

/-- [anyhow::error::{anyhow::Error}::msg]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anyhow-1.0.103/src/error.rs', lines 77:4-79:51
    Name pattern: [anyhow::error::{anyhow::Error}::msg]
    Visibility: public -/
@[rust_fun "anyhow::error::{anyhow::Error}::msg"]
axiom anyhow.error.Error.msg
  {M : Type} (corefmtDisplayInst : core.fmt.Display M) (corefmtDebugInst :
  core.fmt.Debug M) :
  M → Result anyhow.Error

/-- [anyhow::error::{impl core::fmt::Debug for anyhow::Error}::fmt]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anyhow-1.0.103/src/error.rs', lines 708:4-708:64
    Name pattern: [anyhow::error::{core::fmt::Debug<anyhow::Error>}::fmt]
    Visibility: public -/
@[rust_fun "anyhow::error::{core::fmt::Debug<anyhow::Error>}::fmt"]
axiom anyhow.Error.Insts.CoreFmtDebug.fmt
  :
  anyhow.Error → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- [anyhow::__private::format_err]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anyhow-1.0.103/src/lib.rs', lines 684:4-684:47
    Name pattern: [anyhow::__private::format_err]
    Visibility: public -/
@[rust_fun "anyhow::__private::format_err"]
axiom anyhow.__private.format_err : core.fmt.Arguments → Result anyhow.Error

/-- [anyhow::__private::must_use]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anyhow-1.0.103/src/lib.rs', lines 698:4-698:42
    Name pattern: [anyhow::__private::must_use]
    Visibility: public -/
@[rust_fun "anyhow::__private::must_use"]
axiom anyhow.__private.must_use : anyhow.Error → Result anyhow.Error

/-- [hpke_rs::{impl core::fmt::Debug for hpke_rs::HpkeError}::fmt]:
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/src/lib.rs', lines 158:9-158:14
    Name pattern: [hpke_rs::{core::fmt::Debug<hpke_rs::HpkeError>}::fmt]
    Visibility: public -/
@[rust_fun "hpke_rs::{core::fmt::Debug<hpke_rs::HpkeError>}::fmt"]
axiom hpke_rs.HpkeError.Insts.CoreFmtDebug.fmt
  :
  hpke_rs.HpkeError → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- [hpke_rs::{hpke_rs::Hpke<Crypto, Clause0_HpkePrng, Clause0_Clause3_Clause1_Clause0_Error, Clause0_Clause4_Error>}::new]:
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/src/lib.rs', lines 495:4-500:13
    Name pattern: [hpke_rs::{hpke_rs::Hpke<@Crypto, @Clause0_HpkePrng, @Clause0_Clause3_Clause1_Clause0_Error, @Clause0_Clause4_Error>}::new]
    Visibility: public -/
@[rust_fun
  "hpke_rs::{hpke_rs::Hpke<@Crypto, @Clause0_HpkePrng, @Clause0_Clause3_Clause1_Clause0_Error, @Clause0_Clause4_Error>}::new"]
axiom hpke_rs.Hpke.new
  {Crypto : Type} {Clause0_HpkePrng : Type}
  {Clause0_Clause3_Clause1_Clause0_Error : Type} {Clause0_Clause4_Error : Type}
  (hpke_rs_cryptoHpkeCryptoInst : hpke_rs_crypto.HpkeCrypto Crypto
  Clause0_HpkePrng Clause0_Clause3_Clause1_Clause0_Error Clause0_Clause4_Error)
  :
  hpke_rs.Mode → hpke_rs_crypto.types.KemAlgorithm →
    hpke_rs_crypto.types.KdfAlgorithm → hpke_rs_crypto.types.AeadAlgorithm
    → Result (hpke_rs.Hpke Crypto Clause0_HpkePrng
    Clause0_Clause3_Clause1_Clause0_Error Clause0_Clause4_Error)

/-- [hpke_rs::{hpke_rs::Hpke<Crypto, Clause0_HpkePrng, Clause0_Clause3_Clause1_Clause0_Error, Clause0_Clause4_Error>}::seal]:
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/src/lib.rs', lines 609:4-618:60
    Name pattern: [hpke_rs::{hpke_rs::Hpke<@Crypto, @Clause0_HpkePrng, @Clause0_Clause3_Clause1_Clause0_Error, @Clause0_Clause4_Error>}::seal]
    Visibility: public -/
@[rust_fun
  "hpke_rs::{hpke_rs::Hpke<@Crypto, @Clause0_HpkePrng, @Clause0_Clause3_Clause1_Clause0_Error, @Clause0_Clause4_Error>}::seal"]
axiom hpke_rs.Hpke.seal
  {Crypto : Type} {Clause0_HpkePrng : Type}
  {Clause0_Clause3_Clause1_Clause0_Error : Type} {Clause0_Clause4_Error : Type}
  (hpke_rs_cryptoHpkeCryptoInst : hpke_rs_crypto.HpkeCrypto Crypto
  Clause0_HpkePrng Clause0_Clause3_Clause1_Clause0_Error Clause0_Clause4_Error)
  :
  hpke_rs.Hpke Crypto Clause0_HpkePrng Clause0_Clause3_Clause1_Clause0_Error
    Clause0_Clause4_Error → hpke_rs.HpkePublicKey → Slice Std.U8 → Slice
    Std.U8 → Slice Std.U8 → Option (Slice Std.U8) → Option (Slice Std.U8)
    → Option hpke_rs.HpkePrivateKey → Result ((core.result.Result
    ((alloc.vec.Vec Std.U8) × (alloc.vec.Vec Std.U8)) hpke_rs.HpkeError) ×
    (hpke_rs.Hpke Crypto Clause0_HpkePrng Clause0_Clause3_Clause1_Clause0_Error
    Clause0_Clause4_Error))

/-- [hpke_rs::{hpke_rs::Hpke<Crypto, Clause0_HpkePrng, Clause0_Clause3_Clause1_Clause0_Error, Clause0_Clause4_Error>}::open]:
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/src/lib.rs', lines 637:4-647:37
    Name pattern: [hpke_rs::{hpke_rs::Hpke<@Crypto, @Clause0_HpkePrng, @Clause0_Clause3_Clause1_Clause0_Error, @Clause0_Clause4_Error>}::open]
    Visibility: public -/
@[rust_fun
  "hpke_rs::{hpke_rs::Hpke<@Crypto, @Clause0_HpkePrng, @Clause0_Clause3_Clause1_Clause0_Error, @Clause0_Clause4_Error>}::open"]
axiom hpke_rs.Hpke.open
  {Crypto : Type} {Clause0_HpkePrng : Type}
  {Clause0_Clause3_Clause1_Clause0_Error : Type} {Clause0_Clause4_Error : Type}
  (hpke_rs_cryptoHpkeCryptoInst : hpke_rs_crypto.HpkeCrypto Crypto
  Clause0_HpkePrng Clause0_Clause3_Clause1_Clause0_Error Clause0_Clause4_Error)
  :
  hpke_rs.Hpke Crypto Clause0_HpkePrng Clause0_Clause3_Clause1_Clause0_Error
    Clause0_Clause4_Error → Slice Std.U8 → hpke_rs.HpkePrivateKey → Slice
    Std.U8 → Slice Std.U8 → Slice Std.U8 → Option (Slice Std.U8) →
    Option (Slice Std.U8) → Option hpke_rs.HpkePublicKey → Result
    (core.result.Result (alloc.vec.Vec Std.U8) hpke_rs.HpkeError)

/-- [hpke_rs::{impl core::convert::From<alloc::vec::Vec<u8>> for hpke_rs::HpkePrivateKey}::from]:
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/src/lib.rs', lines 916:4-916:31
    Name pattern: [hpke_rs::{core::convert::From<hpke_rs::HpkePrivateKey, alloc::vec::Vec<u8>>}::from]
    Visibility: public -/
@[rust_fun
  "hpke_rs::{core::convert::From<hpke_rs::HpkePrivateKey, alloc::vec::Vec<u8>>}::from"]
axiom hpke_rs.HpkePrivateKey.Insts.CoreConvertFromVecU8.from
  : alloc.vec.Vec Std.U8 → Result hpke_rs.HpkePrivateKey

/-- [hpke_rs::{impl core::convert::From<alloc::vec::Vec<u8>> for hpke_rs::HpkePublicKey}::from]:
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/src/lib.rs', lines 967:4-967:31
    Name pattern: [hpke_rs::{core::convert::From<hpke_rs::HpkePublicKey, alloc::vec::Vec<u8>>}::from]
    Visibility: public -/
@[rust_fun
  "hpke_rs::{core::convert::From<hpke_rs::HpkePublicKey, alloc::vec::Vec<u8>>}::from"]
axiom hpke_rs.HpkePublicKey.Insts.CoreConvertFromVecU8.from
  : alloc.vec.Vec Std.U8 → Result hpke_rs.HpkePublicKey

/-- [hpke_rs_crypto::error::{impl core::fmt::Debug for hpke_rs_crypto::error::Error}::fmt]:
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/traits/src/error.rs', lines 9:9-9:14
    Name pattern: [hpke_rs_crypto::error::{core::fmt::Debug<hpke_rs_crypto::error::Error>}::fmt]
    Visibility: public -/
@[rust_fun
  "hpke_rs_crypto::error::{core::fmt::Debug<hpke_rs_crypto::error::Error>}::fmt"]
axiom hpke_rs_crypto.error.Error.Insts.CoreFmtDebug.fmt
  :
  hpke_rs_crypto.error.Error → core.fmt.Formatter → Result
    ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)

/-- [hpke_rs_crypto::error::{impl core::fmt::Display for hpke_rs_crypto::error::Error}::fmt]:
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/traits/src/error.rs', lines 55:4-55:72
    Name pattern: [hpke_rs_crypto::error::{core::fmt::Display<hpke_rs_crypto::error::Error>}::fmt]
    Visibility: public -/
@[rust_fun
  "hpke_rs_crypto::error::{core::fmt::Display<hpke_rs_crypto::error::Error>}::fmt"]
axiom hpke_rs_crypto.error.Error.Insts.CoreFmtDisplay.fmt
  :
  hpke_rs_crypto.error.Error → core.fmt.Formatter → Result
    ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)

/-- [hpke_rs_libcrux::{impl core::fmt::Debug for hpke_rs_libcrux::HpkeLibcrux}::fmt]:
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/libcrux_provider/src/lib.rs', lines 30:9-30:14
    Name pattern: [hpke_rs_libcrux::{core::fmt::Debug<hpke_rs_libcrux::HpkeLibcrux>}::fmt]
    Visibility: public -/
@[rust_fun
  "hpke_rs_libcrux::{core::fmt::Debug<hpke_rs_libcrux::HpkeLibcrux>}::fmt"]
axiom hpke_rs_libcrux.HpkeLibcrux.Insts.CoreFmtDebug.fmt
  :
  hpke_rs_libcrux.HpkeLibcrux → core.fmt.Formatter → Result
    ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)

/-- [hpke_rs_libcrux::{impl zeroize::Zeroize for hpke_rs_libcrux::HpkeLibcruxPrng}::zeroize]:
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/libcrux_provider/src/lib.rs', lines 41:4-41:25
    Name pattern: [hpke_rs_libcrux::{zeroize::Zeroize<hpke_rs_libcrux::HpkeLibcruxPrng>}::zeroize]
    Visibility: public -/
@[rust_fun
  "hpke_rs_libcrux::{zeroize::Zeroize<hpke_rs_libcrux::HpkeLibcruxPrng>}::zeroize"]
axiom hpke_rs_libcrux.HpkeLibcruxPrng.Insts.ZeroizeZeroize.zeroize
  : hpke_rs_libcrux.HpkeLibcruxPrng → Result hpke_rs_libcrux.HpkeLibcruxPrng

/-- [rand_core::{impl rand_core::Rng for R}::fill_bytes]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_core-0.10.1/src/lib.rs', lines 84:4-84:44
    Name pattern: [rand_core::{rand_core::Rng<@R>}::fill_bytes]
    Visibility: public -/
@[rust_fun "rand_core::{rand_core::Rng<@R>}::fill_bytes"]
axiom rand_core.Rng.Blanket.fill_bytes
  {R : Type} (TryRngRInfallibleInst : rand_core.TryRng R
  core.convert.Infallible) :
  R → Slice Std.U8 → Result (R × (Slice Std.U8))

/-- [rand_core::{impl rand_core::Rng for R}::next_u64]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_core-0.10.1/src/lib.rs', lines 77:4-77:33
    Name pattern: [rand_core::{rand_core::Rng<@R>}::next_u64]
    Visibility: public -/
@[rust_fun "rand_core::{rand_core::Rng<@R>}::next_u64"]
axiom rand_core.Rng.Blanket.next_u64
  {R : Type} (TryRngRInfallibleInst : rand_core.TryRng R
  core.convert.Infallible) :
  R → Result (Std.U64 × R)

/-- [rand_core::{impl rand_core::Rng for R}::next_u32]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_core-0.10.1/src/lib.rs', lines 70:4-70:33
    Name pattern: [rand_core::{rand_core::Rng<@R>}::next_u32]
    Visibility: public -/
@[rust_fun "rand_core::{rand_core::Rng<@R>}::next_u32"]
axiom rand_core.Rng.Blanket.next_u32
  {R : Type} (TryRngRInfallibleInst : rand_core.TryRng R
  core.convert.Infallible) :
  R → Result (Std.U32 × R)

/-- [hpke_rs_libcrux::{impl hpke_rs_crypto::HpkeTestRng<hpke_rs_crypto::error::Error> for hpke_rs_libcrux::HpkeLibcruxPrng}::seed]:
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/libcrux_provider/src/lib.rs', lines 594:4-594:32
    Name pattern: [hpke_rs_libcrux::{hpke_rs_crypto::HpkeTestRng<hpke_rs_libcrux::HpkeLibcruxPrng, hpke_rs_crypto::error::Error>}::seed]
    Visibility: public -/
@[rust_fun
  "hpke_rs_libcrux::{hpke_rs_crypto::HpkeTestRng<hpke_rs_libcrux::HpkeLibcruxPrng, hpke_rs_crypto::error::Error>}::seed"]
axiom hpke_rs_libcrux.HpkeLibcruxPrng.Insts.Hpke_rs_cryptoHpkeTestRngError.seed
  :
  hpke_rs_libcrux.HpkeLibcruxPrng → Slice Std.U8 → Result
    hpke_rs_libcrux.HpkeLibcruxPrng

/-- [hpke_rs_libcrux::{impl hpke_rs_crypto::HpkeTestRng<hpke_rs_crypto::error::Error> for hpke_rs_libcrux::HpkeLibcruxPrng}::try_fill_test_bytes]:
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/libcrux_provider/src/lib.rs', lines 582:4-582:75
    Name pattern: [hpke_rs_libcrux::{hpke_rs_crypto::HpkeTestRng<hpke_rs_libcrux::HpkeLibcruxPrng, hpke_rs_crypto::error::Error>}::try_fill_test_bytes]
    Visibility: public -/
@[rust_fun
  "hpke_rs_libcrux::{hpke_rs_crypto::HpkeTestRng<hpke_rs_libcrux::HpkeLibcruxPrng, hpke_rs_crypto::error::Error>}::try_fill_test_bytes"]
axiom
  hpke_rs_libcrux.HpkeLibcruxPrng.Insts.Hpke_rs_cryptoHpkeTestRngError.try_fill_test_bytes
  :
  hpke_rs_libcrux.HpkeLibcruxPrng → Slice Std.U8 → Result
    ((core.result.Result Unit hpke_rs_crypto.error.Error) ×
    hpke_rs_libcrux.HpkeLibcruxPrng × (Slice Std.U8))

/-- [hpke_rs_libcrux::{impl rand_core::TryRng<core::convert::Infallible> for hpke_rs_libcrux::HpkeLibcruxPrng}::try_fill_bytes]:
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/libcrux_provider/src/lib.rs', lines 563:4-563:75
    Name pattern: [hpke_rs_libcrux::{rand_core::TryRng<hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible>}::try_fill_bytes]
    Visibility: public -/
@[rust_fun
  "hpke_rs_libcrux::{rand_core::TryRng<hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible>}::try_fill_bytes"]
axiom
  hpke_rs_libcrux.HpkeLibcruxPrng.Insts.Rand_coreTryRngInfallible.try_fill_bytes
  :
  hpke_rs_libcrux.HpkeLibcruxPrng → Slice Std.U8 → Result
    ((core.result.Result Unit core.convert.Infallible) ×
    hpke_rs_libcrux.HpkeLibcruxPrng × (Slice Std.U8))

/-- [hpke_rs_libcrux::{impl rand_core::TryRng<core::convert::Infallible> for hpke_rs_libcrux::HpkeLibcruxPrng}::try_next_u64]:
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/libcrux_provider/src/lib.rs', lines 559:4-559:58
    Name pattern: [hpke_rs_libcrux::{rand_core::TryRng<hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible>}::try_next_u64]
    Visibility: public -/
@[rust_fun
  "hpke_rs_libcrux::{rand_core::TryRng<hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible>}::try_next_u64"]
axiom
  hpke_rs_libcrux.HpkeLibcruxPrng.Insts.Rand_coreTryRngInfallible.try_next_u64
  :
  hpke_rs_libcrux.HpkeLibcruxPrng → Result ((core.result.Result Std.U64
    core.convert.Infallible) × hpke_rs_libcrux.HpkeLibcruxPrng)

/-- [hpke_rs_libcrux::{impl rand_core::TryRng<core::convert::Infallible> for hpke_rs_libcrux::HpkeLibcruxPrng}::try_next_u32]:
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/libcrux_provider/src/lib.rs', lines 555:4-555:58
    Name pattern: [hpke_rs_libcrux::{rand_core::TryRng<hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible>}::try_next_u32]
    Visibility: public -/
@[rust_fun
  "hpke_rs_libcrux::{rand_core::TryRng<hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible>}::try_next_u32"]
axiom
  hpke_rs_libcrux.HpkeLibcruxPrng.Insts.Rand_coreTryRngInfallible.try_next_u32
  :
  hpke_rs_libcrux.HpkeLibcruxPrng → Result ((core.result.Result Std.U32
    core.convert.Infallible) × hpke_rs_libcrux.HpkeLibcruxPrng)

/-- [hpke_rs_libcrux::{impl hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error> for hpke_rs_libcrux::HpkeLibcrux}::supports_aead]:
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/libcrux_provider/src/lib.rs', lines 393:4-393:61
    Name pattern: [hpke_rs_libcrux::{hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcrux, hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error>}::supports_aead]
    Visibility: public -/
@[rust_fun
  "hpke_rs_libcrux::{hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcrux, hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error>}::supports_aead"]
axiom
  hpke_rs_libcrux.HpkeLibcrux.Insts.Hpke_rs_cryptoHpkeCryptoHpkeLibcruxPrngInfallibleError.supports_aead
  :
  hpke_rs_crypto.types.AeadAlgorithm → Result (core.result.Result Unit
    hpke_rs_crypto.error.Error)

/-- [hpke_rs_libcrux::{impl hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error> for hpke_rs_libcrux::HpkeLibcrux}::supports_kem]:
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/libcrux_provider/src/lib.rs', lines 379:4-379:59
    Name pattern: [hpke_rs_libcrux::{hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcrux, hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error>}::supports_kem]
    Visibility: public -/
@[rust_fun
  "hpke_rs_libcrux::{hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcrux, hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error>}::supports_kem"]
axiom
  hpke_rs_libcrux.HpkeLibcrux.Insts.Hpke_rs_cryptoHpkeCryptoHpkeLibcruxPrngInfallibleError.supports_kem
  :
  hpke_rs_crypto.types.KemAlgorithm → Result (core.result.Result Unit
    hpke_rs_crypto.error.Error)

/-- [hpke_rs_libcrux::{impl hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error> for hpke_rs_libcrux::HpkeLibcrux}::supports_kdf]:
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/libcrux_provider/src/lib.rs', lines 374:4-374:57
    Name pattern: [hpke_rs_libcrux::{hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcrux, hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error>}::supports_kdf]
    Visibility: public -/
@[rust_fun
  "hpke_rs_libcrux::{hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcrux, hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error>}::supports_kdf"]
axiom
  hpke_rs_libcrux.HpkeLibcrux.Insts.Hpke_rs_cryptoHpkeCryptoHpkeLibcruxPrngInfallibleError.supports_kdf
  :
  hpke_rs_crypto.types.KdfAlgorithm → Result (core.result.Result Unit
    hpke_rs_crypto.error.Error)

/-- [hpke_rs_libcrux::{impl hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error> for hpke_rs_libcrux::HpkeLibcrux}::prng]:
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/libcrux_provider/src/lib.rs', lines 356:4-356:31
    Name pattern: [hpke_rs_libcrux::{hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcrux, hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error>}::prng]
    Visibility: public -/
@[rust_fun
  "hpke_rs_libcrux::{hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcrux, hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error>}::prng"]
axiom
  hpke_rs_libcrux.HpkeLibcrux.Insts.Hpke_rs_cryptoHpkeCryptoHpkeLibcruxPrngInfallibleError.prng
  : Result hpke_rs_libcrux.HpkeLibcruxPrng

/-- [hpke_rs_libcrux::{impl hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error> for hpke_rs_libcrux::HpkeLibcrux}::aead_open]:
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/libcrux_provider/src/lib.rs', lines 311:4-317:31
    Name pattern: [hpke_rs_libcrux::{hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcrux, hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error>}::aead_open]
    Visibility: public -/
@[rust_fun
  "hpke_rs_libcrux::{hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcrux, hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error>}::aead_open"]
axiom
  hpke_rs_libcrux.HpkeLibcrux.Insts.Hpke_rs_cryptoHpkeCryptoHpkeLibcruxPrngInfallibleError.aead_open
  :
  hpke_rs_crypto.types.AeadAlgorithm → Slice Std.U8 → Slice Std.U8 →
    Slice Std.U8 → Slice Std.U8 → Result (core.result.Result (alloc.vec.Vec
    Std.U8) hpke_rs_crypto.error.Error)

/-- [hpke_rs_libcrux::{impl hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error> for hpke_rs_libcrux::HpkeLibcrux}::aead_seal]:
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/libcrux_provider/src/lib.rs', lines 277:4-283:31
    Name pattern: [hpke_rs_libcrux::{hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcrux, hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error>}::aead_seal]
    Visibility: public -/
@[rust_fun
  "hpke_rs_libcrux::{hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcrux, hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error>}::aead_seal"]
axiom
  hpke_rs_libcrux.HpkeLibcrux.Insts.Hpke_rs_cryptoHpkeCryptoHpkeLibcruxPrngInfallibleError.aead_seal
  :
  hpke_rs_crypto.types.AeadAlgorithm → Slice Std.U8 → Slice Std.U8 →
    Slice Std.U8 → Slice Std.U8 → Result (core.result.Result (alloc.vec.Vec
    Std.U8) hpke_rs_crypto.error.Error)

/-- [hpke_rs_libcrux::{impl hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error> for hpke_rs_libcrux::HpkeLibcrux}::dh_validate_sk]:
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/libcrux_provider/src/lib.rs', lines 260:4-260:77
    Name pattern: [hpke_rs_libcrux::{hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcrux, hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error>}::dh_validate_sk]
    Visibility: public -/
@[rust_fun
  "hpke_rs_libcrux::{hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcrux, hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error>}::dh_validate_sk"]
axiom
  hpke_rs_libcrux.HpkeLibcrux.Insts.Hpke_rs_cryptoHpkeCryptoHpkeLibcruxPrngInfallibleError.dh_validate_sk
  :
  hpke_rs_crypto.types.KemAlgorithm → Slice Std.U8 → Result
    (core.result.Result (alloc.vec.Vec Std.U8) hpke_rs_crypto.error.Error)

/-- [hpke_rs_libcrux::{impl hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error> for hpke_rs_libcrux::HpkeLibcrux}::kem_decaps]:
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/libcrux_provider/src/lib.rs', lines 237:4-237:86
    Name pattern: [hpke_rs_libcrux::{hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcrux, hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error>}::kem_decaps]
    Visibility: public -/
@[rust_fun
  "hpke_rs_libcrux::{hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcrux, hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error>}::kem_decaps"]
axiom
  hpke_rs_libcrux.HpkeLibcrux.Insts.Hpke_rs_cryptoHpkeCryptoHpkeLibcruxPrngInfallibleError.kem_decaps
  :
  hpke_rs_crypto.types.KemAlgorithm → Slice Std.U8 → Slice Std.U8 →
    Result (core.result.Result (alloc.vec.Vec Std.U8)
    hpke_rs_crypto.error.Error)

/-- [hpke_rs_libcrux::{impl hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error> for hpke_rs_libcrux::HpkeLibcrux}::kem_encaps]:
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/libcrux_provider/src/lib.rs', lines 211:4-215:42
    Name pattern: [hpke_rs_libcrux::{hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcrux, hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error>}::kem_encaps]
    Visibility: public -/
@[rust_fun
  "hpke_rs_libcrux::{hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcrux, hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error>}::kem_encaps"]
axiom
  hpke_rs_libcrux.HpkeLibcrux.Insts.Hpke_rs_cryptoHpkeCryptoHpkeLibcruxPrngInfallibleError.kem_encaps
  :
  hpke_rs_crypto.types.KemAlgorithm → Slice Std.U8 →
    hpke_rs_libcrux.HpkeLibcruxPrng → Result ((core.result.Result
    ((alloc.vec.Vec Std.U8) × (alloc.vec.Vec Std.U8))
    hpke_rs_crypto.error.Error) × hpke_rs_libcrux.HpkeLibcruxPrng)

/-- [hpke_rs_libcrux::{impl hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error> for hpke_rs_libcrux::HpkeLibcrux}::kem_key_gen_derand]:
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/libcrux_provider/src/lib.rs', lines 176:4-176:94
    Name pattern: [hpke_rs_libcrux::{hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcrux, hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error>}::kem_key_gen_derand]
    Visibility: public -/
@[rust_fun
  "hpke_rs_libcrux::{hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcrux, hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error>}::kem_key_gen_derand"]
axiom
  hpke_rs_libcrux.HpkeLibcrux.Insts.Hpke_rs_cryptoHpkeCryptoHpkeLibcruxPrngInfallibleError.kem_key_gen_derand
  :
  hpke_rs_crypto.types.KemAlgorithm → Slice Std.U8 → Result
    (core.result.Result ((alloc.vec.Vec Std.U8) × (alloc.vec.Vec Std.U8))
    hpke_rs_crypto.error.Error)

/-- [hpke_rs_libcrux::{impl hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error> for hpke_rs_libcrux::HpkeLibcrux}::kem_key_gen]:
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/libcrux_provider/src/lib.rs', lines 130:4-133:42
    Name pattern: [hpke_rs_libcrux::{hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcrux, hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error>}::kem_key_gen]
    Visibility: public -/
@[rust_fun
  "hpke_rs_libcrux::{hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcrux, hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error>}::kem_key_gen"]
axiom
  hpke_rs_libcrux.HpkeLibcrux.Insts.Hpke_rs_cryptoHpkeCryptoHpkeLibcruxPrngInfallibleError.kem_key_gen
  :
  hpke_rs_crypto.types.KemAlgorithm → hpke_rs_libcrux.HpkeLibcruxPrng →
    Result ((core.result.Result ((alloc.vec.Vec Std.U8) × (alloc.vec.Vec
    Std.U8)) hpke_rs_crypto.error.Error) × hpke_rs_libcrux.HpkeLibcruxPrng)

/-- [hpke_rs_libcrux::{impl hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error> for hpke_rs_libcrux::HpkeLibcrux}::secret_to_public]:
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/libcrux_provider/src/lib.rs', lines 111:4-111:79
    Name pattern: [hpke_rs_libcrux::{hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcrux, hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error>}::secret_to_public]
    Visibility: public -/
@[rust_fun
  "hpke_rs_libcrux::{hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcrux, hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error>}::secret_to_public"]
axiom
  hpke_rs_libcrux.HpkeLibcrux.Insts.Hpke_rs_cryptoHpkeCryptoHpkeLibcruxPrngInfallibleError.secret_to_public
  :
  hpke_rs_crypto.types.KemAlgorithm → Slice Std.U8 → Result
    (core.result.Result (alloc.vec.Vec Std.U8) hpke_rs_crypto.error.Error)

/-- [hpke_rs_libcrux::{impl hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error> for hpke_rs_libcrux::HpkeLibcrux}::dh]:
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/libcrux_provider/src/lib.rs', lines 72:4-72:76
    Name pattern: [hpke_rs_libcrux::{hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcrux, hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error>}::dh]
    Visibility: public -/
@[rust_fun
  "hpke_rs_libcrux::{hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcrux, hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error>}::dh"]
axiom
  hpke_rs_libcrux.HpkeLibcrux.Insts.Hpke_rs_cryptoHpkeCryptoHpkeLibcruxPrngInfallibleError.dh
  :
  hpke_rs_crypto.types.KemAlgorithm → Slice Std.U8 → Slice Std.U8 →
    Result (core.result.Result (alloc.vec.Vec Std.U8)
    hpke_rs_crypto.error.Error)

/-- [hpke_rs_libcrux::{impl hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error> for hpke_rs_libcrux::HpkeLibcrux}::kdf_expand]:
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/libcrux_provider/src/lib.rs', lines 59:4-64:31
    Name pattern: [hpke_rs_libcrux::{hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcrux, hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error>}::kdf_expand]
    Visibility: public -/
@[rust_fun
  "hpke_rs_libcrux::{hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcrux, hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error>}::kdf_expand"]
axiom
  hpke_rs_libcrux.HpkeLibcrux.Insts.Hpke_rs_cryptoHpkeCryptoHpkeLibcruxPrngInfallibleError.kdf_expand
  :
  hpke_rs_crypto.types.KdfAlgorithm → Slice Std.U8 → Slice Std.U8 →
    Std.Usize → Result (core.result.Result (alloc.vec.Vec Std.U8)
    hpke_rs_crypto.error.Error)

/-- [hpke_rs_libcrux::{impl hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error> for hpke_rs_libcrux::HpkeLibcrux}::kdf_extract]:
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/libcrux_provider/src/lib.rs', lines 51:4-51:88
    Name pattern: [hpke_rs_libcrux::{hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcrux, hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error>}::kdf_extract]
    Visibility: public -/
@[rust_fun
  "hpke_rs_libcrux::{hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcrux, hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error>}::kdf_extract"]
axiom
  hpke_rs_libcrux.HpkeLibcrux.Insts.Hpke_rs_cryptoHpkeCryptoHpkeLibcruxPrngInfallibleError.kdf_extract
  :
  hpke_rs_crypto.types.KdfAlgorithm → Slice Std.U8 → Slice Std.U8 →
    Result (core.result.Result (alloc.vec.Vec Std.U8)
    hpke_rs_crypto.error.Error)

/-- [hpke_rs_libcrux::{impl hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error> for hpke_rs_libcrux::HpkeLibcrux}::name]:
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/libcrux_provider/src/lib.rs', lines 47:4-47:23
    Name pattern: [hpke_rs_libcrux::{hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcrux, hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error>}::name]
    Visibility: public -/
@[rust_fun
  "hpke_rs_libcrux::{hpke_rs_crypto::HpkeCrypto<hpke_rs_libcrux::HpkeLibcrux, hpke_rs_libcrux::HpkeLibcruxPrng, core::convert::Infallible, hpke_rs_crypto::error::Error>}::name"]
axiom
  hpke_rs_libcrux.HpkeLibcrux.Insts.Hpke_rs_cryptoHpkeCryptoHpkeLibcruxPrngInfallibleError.name
  : Result String

/-- [libcrux_curve25519::impl_hacl::ecdh]:
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/crates/algorithms/curve25519/src/impl_hacl.rs', lines 13:0-13:94
    Name pattern: [libcrux_curve25519::impl_hacl::ecdh]
    Visibility: public -/
@[rust_fun "libcrux_curve25519::impl_hacl::ecdh"]
axiom libcrux_curve25519.impl_hacl.ecdh
  :
  Array Std.U8 32#usize → Array Std.U8 32#usize → Array Std.U8 32#usize →
    Result ((core.result.Result Unit libcrux_curve25519.Error) × (Array Std.U8
    32#usize))

/-- [libcrux_kem::{impl core::fmt::Debug for libcrux_kem::Error}::fmt]:
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/libcrux-kem/src/kem.rs', lines 116:9-116:14
    Name pattern: [libcrux_kem::{core::fmt::Debug<libcrux_kem::Error>}::fmt]
    Visibility: public -/
@[rust_fun "libcrux_kem::{core::fmt::Debug<libcrux_kem::Error>}::fmt"]
axiom libcrux_kem.Error.Insts.CoreFmtDebug.fmt
  :
  libcrux_kem.Error → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- [libcrux_kem::{libcrux_kem::PrivateKey}::encode]:
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/libcrux-kem/src/kem.rs', lines 399:4-399:35
    Name pattern: [libcrux_kem::{libcrux_kem::PrivateKey}::encode]
    Visibility: public -/
@[rust_fun "libcrux_kem::{libcrux_kem::PrivateKey}::encode"]
axiom libcrux_kem.PrivateKey.encode
  : libcrux_kem.PrivateKey → Result (alloc.vec.Vec Std.U8)

/-- [libcrux_kem::{libcrux_kem::PublicKey}::encode]:
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/libcrux-kem/src/kem.rs', lines 595:4-595:35
    Name pattern: [libcrux_kem::{libcrux_kem::PublicKey}::encode]
    Visibility: public -/
@[rust_fun "libcrux_kem::{libcrux_kem::PublicKey}::encode"]
axiom libcrux_kem.PublicKey.encode
  : libcrux_kem.PublicKey → Result (alloc.vec.Vec Std.U8)

/-- [libcrux_kem::key_gen]:
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/libcrux-kem/src/kem.rs', lines 769:0-769:98
    Name pattern: [libcrux_kem::key_gen]
    Visibility: public -/
@[rust_fun "libcrux_kem::key_gen"]
axiom libcrux_kem.key_gen
  {T0 : Type} {Clause0_Clause1_Clause0_Error : Type} (rand_coreCryptoRngInst :
  rand_core.CryptoRng T0 Clause0_Clause1_Clause0_Error) :
  libcrux_kem.Algorithm → T0 → Result ((core.result.Result
    (libcrux_kem.PrivateKey × libcrux_kem.PublicKey) libcrux_kem.Error) × T0)

/-- [libcrux_kem::key_gen_derand]:
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/libcrux-kem/src/kem.rs', lines 829:0-829:92
    Name pattern: [libcrux_kem::key_gen_derand]
    Visibility: public -/
@[rust_fun "libcrux_kem::key_gen_derand"]
axiom libcrux_kem.key_gen_derand
  :
  libcrux_kem.Algorithm → Slice Std.U8 → Result (core.result.Result
    (libcrux_kem.PrivateKey × libcrux_kem.PublicKey) libcrux_kem.Error)

/-- [libcrux_ml_kem::mlkem768::{impl libcrux_traits::kem::arrayref::Kem<1184usize, 2400usize, 1088usize, 32usize, 64usize, 32usize> for libcrux_ml_kem::mlkem768::MlKem768}::decaps]:
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/libcrux-ml-kem/src/lib.rs', lines 157:12-161:68
    Name pattern: [libcrux_ml_kem::mlkem768::{libcrux_traits::kem::arrayref::Kem<libcrux_ml_kem::mlkem768::MlKem768, 1184, 2400, 1088, 32, 64, 32>}::decaps]
    Visibility: public -/
@[rust_fun
  "libcrux_ml_kem::mlkem768::{libcrux_traits::kem::arrayref::Kem<libcrux_ml_kem::mlkem768::MlKem768, 1184, 2400, 1088, 32, 64, 32>}::decaps"]
axiom
  libcrux_ml_kem.mlkem768.MlKem768.Insts.Libcrux_traitsKemArrayrefKem118424001088326432.decaps
  :
  Array Std.U8 32#usize → Array Std.U8 1088#usize → Array Std.U8 2400#usize
    → Result ((core.result.Result Unit
    libcrux_traits.kem.arrayref.DecapsError) × (Array Std.U8 32#usize))

/-- [libcrux_ml_kem::mlkem768::{impl libcrux_traits::kem::arrayref::Kem<1184usize, 2400usize, 1088usize, 32usize, 64usize, 32usize> for libcrux_ml_kem::mlkem768::MlKem768}::encaps]:
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/libcrux-ml-kem/src/lib.rs', lines 142:12-147:68
    Name pattern: [libcrux_ml_kem::mlkem768::{libcrux_traits::kem::arrayref::Kem<libcrux_ml_kem::mlkem768::MlKem768, 1184, 2400, 1088, 32, 64, 32>}::encaps]
    Visibility: public -/
@[rust_fun
  "libcrux_ml_kem::mlkem768::{libcrux_traits::kem::arrayref::Kem<libcrux_ml_kem::mlkem768::MlKem768, 1184, 2400, 1088, 32, 64, 32>}::encaps"]
axiom
  libcrux_ml_kem.mlkem768.MlKem768.Insts.Libcrux_traitsKemArrayrefKem118424001088326432.encaps
  :
  Array Std.U8 1088#usize → Array Std.U8 32#usize → Array Std.U8 1184#usize
    → Array Std.U8 32#usize → Result ((core.result.Result Unit
    libcrux_traits.kem.arrayref.EncapsError) × (Array Std.U8 1088#usize) ×
    (Array Std.U8 32#usize))

/-- [libcrux_ml_kem::mlkem768::{impl libcrux_traits::kem::arrayref::Kem<1184usize, 2400usize, 1088usize, 32usize, 64usize, 32usize> for libcrux_ml_kem::mlkem768::MlKem768}::keygen]:
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/libcrux-ml-kem/src/lib.rs', lines 130:12-134:68
    Name pattern: [libcrux_ml_kem::mlkem768::{libcrux_traits::kem::arrayref::Kem<libcrux_ml_kem::mlkem768::MlKem768, 1184, 2400, 1088, 32, 64, 32>}::keygen]
    Visibility: public -/
@[rust_fun
  "libcrux_ml_kem::mlkem768::{libcrux_traits::kem::arrayref::Kem<libcrux_ml_kem::mlkem768::MlKem768, 1184, 2400, 1088, 32, 64, 32>}::keygen"]
axiom
  libcrux_ml_kem.mlkem768.MlKem768.Insts.Libcrux_traitsKemArrayrefKem118424001088326432.keygen
  :
  Array Std.U8 1184#usize → Array Std.U8 2400#usize → Array Std.U8 64#usize
    → Result ((core.result.Result Unit
    libcrux_traits.kem.arrayref.KeyGenError) × (Array Std.U8 1184#usize) ×
    (Array Std.U8 2400#usize))

/-- [libcrux_traits::kem::arrayref::{impl core::fmt::Debug for libcrux_traits::kem::arrayref::EncapsError}::fmt]:
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/traits/src/kem/arrayref.rs', lines 55:9-55:14
    Name pattern: [libcrux_traits::kem::arrayref::{core::fmt::Debug<libcrux_traits::kem::arrayref::EncapsError>}::fmt]
    Visibility: public -/
@[rust_fun
  "libcrux_traits::kem::arrayref::{core::fmt::Debug<libcrux_traits::kem::arrayref::EncapsError>}::fmt"]
axiom libcrux_traits.kem.arrayref.EncapsError.Insts.CoreFmtDebug.fmt
  :
  libcrux_traits.kem.arrayref.EncapsError → core.fmt.Formatter → Result
    ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)

/-- [libcrux_traits::kem::arrayref::{impl core::fmt::Debug for libcrux_traits::kem::arrayref::DecapsError}::fmt]:
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/traits/src/kem/arrayref.rs', lines 68:9-68:14
    Name pattern: [libcrux_traits::kem::arrayref::{core::fmt::Debug<libcrux_traits::kem::arrayref::DecapsError>}::fmt]
    Visibility: public -/
@[rust_fun
  "libcrux_traits::kem::arrayref::{core::fmt::Debug<libcrux_traits::kem::arrayref::DecapsError>}::fmt"]
axiom libcrux_traits.kem.arrayref.DecapsError.Insts.CoreFmtDebug.fmt
  :
  libcrux_traits.kem.arrayref.DecapsError → core.fmt.Formatter → Result
    ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)

/-- [libcrux_traits::kem::owned::{impl libcrux_traits::kem::owned::Kem<EK_LEN, DK_LEN, CT_LEN, SS_LEN, RAND_KEYGEN_LEN, RAND_ENCAPS_LEN> for T}::encaps]:
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/traits/src/kem/owned.rs', lines 64:4-67:58
    Name pattern: [libcrux_traits::kem::owned::{libcrux_traits::kem::owned::Kem<@T, @EK_LEN, @DK_LEN, @CT_LEN, @SS_LEN, @RAND_KEYGEN_LEN, @RAND_ENCAPS_LEN>}::encaps]
    Visibility: public -/
@[rust_fun
  "libcrux_traits::kem::owned::{libcrux_traits::kem::owned::Kem<@T, @EK_LEN, @DK_LEN, @CT_LEN, @SS_LEN, @RAND_KEYGEN_LEN, @RAND_ENCAPS_LEN>}::encaps"]
axiom libcrux_traits.kem.owned.Kem.Blanket.encaps
  {T : Type} {EK_LEN : Std.Usize} {DK_LEN : Std.Usize} {CT_LEN : Std.Usize}
  {SS_LEN : Std.Usize} {RAND_KEYGEN_LEN : Std.Usize} {RAND_ENCAPS_LEN :
  Std.Usize} (arrayrefKemInst : libcrux_traits.kem.arrayref.Kem T EK_LEN DK_LEN
  CT_LEN SS_LEN RAND_KEYGEN_LEN RAND_ENCAPS_LEN) :
  Array Std.U8 EK_LEN → Array Std.U8 RAND_ENCAPS_LEN → Result
    (core.result.Result ((Array Std.U8 SS_LEN) × (Array Std.U8 CT_LEN))
    libcrux_traits.kem.arrayref.EncapsError)

/-- [libcrux_traits::kem::owned::{impl libcrux_traits::kem::owned::Kem<EK_LEN, DK_LEN, CT_LEN, SS_LEN, RAND_KEYGEN_LEN, RAND_ENCAPS_LEN> for T}::decaps]:
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/traits/src/kem/owned.rs', lines 83:4-83:88
    Name pattern: [libcrux_traits::kem::owned::{libcrux_traits::kem::owned::Kem<@T, @EK_LEN, @DK_LEN, @CT_LEN, @SS_LEN, @RAND_KEYGEN_LEN, @RAND_ENCAPS_LEN>}::decaps]
    Visibility: public -/
@[rust_fun
  "libcrux_traits::kem::owned::{libcrux_traits::kem::owned::Kem<@T, @EK_LEN, @DK_LEN, @CT_LEN, @SS_LEN, @RAND_KEYGEN_LEN, @RAND_ENCAPS_LEN>}::decaps"]
axiom libcrux_traits.kem.owned.Kem.Blanket.decaps
  {T : Type} {EK_LEN : Std.Usize} {DK_LEN : Std.Usize} {CT_LEN : Std.Usize}
  {SS_LEN : Std.Usize} {RAND_KEYGEN_LEN : Std.Usize} {RAND_ENCAPS_LEN :
  Std.Usize} (arrayrefKemInst : libcrux_traits.kem.arrayref.Kem T EK_LEN DK_LEN
  CT_LEN SS_LEN RAND_KEYGEN_LEN RAND_ENCAPS_LEN) :
  Array Std.U8 CT_LEN → Array Std.U8 DK_LEN → Result (core.result.Result
    (Array Std.U8 SS_LEN) libcrux_traits.kem.arrayref.DecapsError)

/-- [securedrop_protocol_minimal::primitives::provider::rng::fill_bytes]:
    Source: 'protocol-minimal/src/primitives/provider.rs', lines 81:4-86:5 -/
axiom primitives.provider.rng.fill_bytes
  {R : Type} {Clause1_Clause1_Clause0_Error : Type} {N : Std.Usize}
  (rand_coreRngCoreInst : rand_core.RngCore R) (rand_coreCryptoRngInst :
  rand_core.CryptoRng R Clause1_Clause1_Clause0_Error) :
  R → Array Std.U8 N → Result (R × (Array Std.U8 N))

/-- [securedrop_protocol_minimal::primitives::provider::curve25519::x25519_keygen]:
    Source: 'protocol-minimal/src/primitives/provider.rs', lines 22:4-28:5 -/
axiom primitives.provider.curve25519.x25519_keygen
  :
  Array Std.U8 32#usize → Array Std.U8 32#usize → Array Std.U8 32#usize →
    Result ((core.result.Result Unit libcrux_traits.kem.arrayref.KeyGenError)
    × (Array Std.U8 32#usize) × (Array Std.U8 32#usize))

/-- [securedrop_protocol_minimal::encrypt_decrypt::decrypt_with_sender]:
    Source: 'protocol-minimal/src/encrypt_decrypt.rs', lines 86:0-120:1
    Visibility: public -/
axiom encrypt_decrypt.decrypt_with_sender
  {U : Type} (traitsUserSecretInst : traits.UserSecret U) :
  U → ciphertext.Envelope → Result (ciphertext.Plaintext ×
    message.MessagePublicKey)

/-- [securedrop_protocol_minimal::primitives::provider::curve25519::PK_LEN]
    Source: 'protocol-minimal/src/primitives/provider.rs', lines 10:4-10:64 -/
axiom primitives.provider.curve25519.PK_LEN : Result Std.Usize

/-- [securedrop_protocol_minimal::primitives::provider::curve25519::LEN_DH_SHARE]
    Source: 'protocol-minimal/src/primitives/provider.rs', lines 13:4-13:70 -/
axiom primitives.provider.curve25519.LEN_DH_SHARE : Result Std.Usize

/-- [securedrop_protocol_minimal::primitives::provider::curve25519::SK_LEN]
    Source: 'protocol-minimal/src/primitives/provider.rs', lines 7:4-7:64 -/
axiom primitives.provider.curve25519.SK_LEN : Result Std.Usize

/-- [securedrop_protocol_minimal::primitives::provider::ed25519::keygen]:
    Source: 'protocol-minimal/src/primitives/provider.rs', lines 36:4-40:5 -/
axiom primitives.provider.ed25519.keygen
  {R : Type} {Clause0_Clause1_Clause0_Error : Type} (rand_coreCryptoRngInst :
  rand_core.CryptoRng R Clause0_Clause1_Clause0_Error) :
  R → Result ((core.result.Result ((Array Std.U8 32#usize) × (Array Std.U8
    32#usize)) anyhow.Error) × R)

/-- [securedrop_protocol_minimal::primitives::provider::ed25519::sign]:
    Source: 'protocol-minimal/src/primitives/provider.rs', lines 49:4-51:5 -/
axiom primitives.provider.ed25519.sign
  : Slice Std.U8 → Array Std.U8 32#usize → Result (Array Std.U8 64#usize)

/-- [securedrop_protocol_minimal::primitives::provider::ed25519::verify]:
    Source: 'protocol-minimal/src/primitives/provider.rs', lines 60:4-67:5 -/
axiom primitives.provider.ed25519.verify
  :
  Slice Std.U8 → Array Std.U8 32#usize → Array Std.U8 64#usize → Result
    (core.result.Result Unit anyhow.Error)

/-- [securedrop_protocol_minimal::primitives::provider::ed25519::secret_to_public]:
    Source: 'protocol-minimal/src/primitives/provider.rs', lines 71:4-73:5 -/
axiom primitives.provider.ed25519.secret_to_public
  :
  Array Std.U8 32#usize → Array Std.U8 32#usize → Result (Array Std.U8
    32#usize)

/-- [securedrop_protocol_minimal::sign::{impl securedrop_protocol_minimal::sign::DomainTag for securedrop_protocol_minimal::sign::JournalistLongTermKey}::tag]:
    Source: 'protocol-minimal/src/sign.rs', lines 65:4-67:5
    Visibility: public -/
axiom
  sign.JournalistLongTermKey.Insts.Securedrop_protocol_minimalSignDomainTag.tag
  : Result (Slice Std.U8)

/-- [securedrop_protocol_minimal::sign::{impl securedrop_protocol_minimal::sign::DomainTag for securedrop_protocol_minimal::sign::JournalistEphemeralKey}::tag]:
    Source: 'protocol-minimal/src/sign.rs', lines 71:4-73:5
    Visibility: public -/
axiom
  sign.JournalistEphemeralKey.Insts.Securedrop_protocol_minimalSignDomainTag.tag
  : Result (Slice Std.U8)

/-- [securedrop_protocol_minimal::sign::{impl securedrop_protocol_minimal::sign::DomainTag for securedrop_protocol_minimal::sign::NewsroomOnJournalist}::tag]:
    Source: 'protocol-minimal/src/sign.rs', lines 77:4-79:5
    Visibility: public -/
axiom
  sign.NewsroomOnJournalist.Insts.Securedrop_protocol_minimalSignDomainTag.tag
  : Result (Slice Std.U8)

/-- [securedrop_protocol_minimal::sign::{impl securedrop_protocol_minimal::sign::DomainTag for securedrop_protocol_minimal::sign::FpfOnNewsroom}::tag]:
    Source: 'protocol-minimal/src/sign.rs', lines 83:4-85:5
    Visibility: public -/
axiom sign.FpfOnNewsroom.Insts.Securedrop_protocol_minimalSignDomainTag.tag
  : Result (Slice Std.U8)

/-- [securedrop_protocol_minimal::sign::tagged_preimage]:
    Source: 'protocol-minimal/src/sign.rs', lines 167:0-179:1 -/
axiom sign.tagged_preimage
  {D : Type} (DomainTagInst : sign.DomainTag D) :
  Slice Std.U8 → Result (alloc.vec.Vec Std.U8)

