-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [securedrop_protocol_minimal]: type definitions
import Aeneas
import SecuredropProtocolMinimal.Extraction.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace securedrop_protocol_minimal

/-- [core::marker::PhantomData]
    Source: '/rustc/library/core/src/marker.rs', lines 811:0-811:39
    Name pattern: [core::marker::PhantomData]
    Visibility: public -/
@[reducible, rust_type "core::marker::PhantomData"]
def core.marker.PhantomData (T : Type) := Unit

/-- [hpke_rs::HpkeError]
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/src/lib.rs', lines 159:0-159:18
    Name pattern: [hpke_rs::HpkeError]
    Visibility: public -/
@[discriminant isize, rust_type "hpke_rs::HpkeError"]
inductive hpke_rs.HpkeError where
| OpenError : hpke_rs.HpkeError
| InvalidConfig : hpke_rs.HpkeError
| InvalidInput : hpke_rs.HpkeError
| UnknownMode : hpke_rs.HpkeError
| InconsistentPsk : hpke_rs.HpkeError
| MissingPsk : hpke_rs.HpkeError
| UnnecessaryPsk : hpke_rs.HpkeError
| InsecurePsk : hpke_rs.HpkeError
| CryptoError : String → hpke_rs.HpkeError
| MessageLimitReached : hpke_rs.HpkeError
| InsufficientRandomness : hpke_rs.HpkeError

/-- [hpke_rs::Mode]
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/src/lib.rs', lines 256:0-256:13
    Name pattern: [hpke_rs::Mode]
    Visibility: public -/
@[discriminant u8, rust_type "hpke_rs::Mode"]
inductive hpke_rs.Mode where
| Base : hpke_rs.Mode
| Psk : hpke_rs.Mode
| Auth : hpke_rs.Mode
| AuthPsk : hpke_rs.Mode

/-- Trait declaration: [zeroize::Zeroize]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.8.2/src/lib.rs', lines 272:0-272:17
    Name pattern: [zeroize::Zeroize]
    Visibility: public -/
@[rust_trait "zeroize::Zeroize"]
structure zeroize.Zeroize (Self : Type) where
  zeroize : Self → Result Self

/-- Trait declaration: [rand_core::TryRng]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_core-0.10.1/src/lib.rs', lines 189:0-189:16
    Name pattern: [rand_core::TryRng]
    Visibility: public -/
@[rust_trait "rand_core::TryRng" (parentClauses := ["coreerrorErrorInst"])]
structure rand_core.TryRng (Self : Type) (Self_Error : Type) where
  coreerrorErrorInst : core.error.Error Self_Error
  try_next_u32 : Self → Result ((core.result.Result Std.U32 Self_Error) ×
    Self)
  try_next_u64 : Self → Result ((core.result.Result Std.U64 Self_Error) ×
    Self)
  try_fill_bytes : Self → Slice Std.U8 → Result ((core.result.Result Unit
    Self_Error) × Self × (Slice Std.U8))

/-- Trait declaration: [rand_core::TryCryptoRng]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_core-0.10.1/src/lib.rs', lines 249:0-249:30
    Name pattern: [rand_core::TryCryptoRng]
    Visibility: public -/
@[rust_trait "rand_core::TryCryptoRng" (parentClauses := ["TryRngInst"])]
structure rand_core.TryCryptoRng (Self : Type) (Self_Clause0_Error : Type)
  where
  TryRngInst : rand_core.TryRng Self Self_Clause0_Error

/-- Trait declaration: [rand_core::Rng]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_core-0.10.1/src/lib.rs', lines 49:0-49:41
    Name pattern: [rand_core::Rng]
    Visibility: public -/
@[rust_trait "rand_core::Rng" (parentClauses := ["TryRngSelfInfallibleInst"])]
structure rand_core.Rng (Self : Type) where
  TryRngSelfInfallibleInst : rand_core.TryRng Self core.convert.Infallible
  next_u32 : Self → Result (Std.U32 × Self)
  next_u64 : Self → Result (Std.U64 × Self)
  fill_bytes : Self → Slice Std.U8 → Result (Self × (Slice Std.U8))

/-- Trait declaration: [rand_core::CryptoRng]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_core-0.10.1/src/lib.rs', lines 95:0-95:59
    Name pattern: [rand_core::CryptoRng]
    Visibility: public -/
@[rust_trait "rand_core::CryptoRng"
  (parentClauses := ["RngInst", "TryCryptoRngInst"])]
structure rand_core.CryptoRng (Self : Type) (Self_Clause1_Clause0_Error : Type)
  where
  RngInst : rand_core.Rng Self
  TryCryptoRngInst : rand_core.TryCryptoRng Self Self_Clause1_Clause0_Error

/-- [hpke_rs_crypto::types::KdfAlgorithm]
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/traits/src/types.rs', lines 217:0-217:21
    Name pattern: [hpke_rs_crypto::types::KdfAlgorithm]
    Visibility: public -/
@[discriminant u16 [1,2,3], rust_type "hpke_rs_crypto::types::KdfAlgorithm"]
inductive hpke_rs_crypto.types.KdfAlgorithm where
| HkdfSha256 : hpke_rs_crypto.types.KdfAlgorithm
| HkdfSha384 : hpke_rs_crypto.types.KdfAlgorithm
| HkdfSha512 : hpke_rs_crypto.types.KdfAlgorithm

/-- [hpke_rs_crypto::types::AeadAlgorithm]
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/traits/src/types.rs', lines 127:0-127:22
    Name pattern: [hpke_rs_crypto::types::AeadAlgorithm]
    Visibility: public -/
@[discriminant u16 [1,2,3,65535], rust_type
  "hpke_rs_crypto::types::AeadAlgorithm"]
inductive hpke_rs_crypto.types.AeadAlgorithm where
| Aes128Gcm : hpke_rs_crypto.types.AeadAlgorithm
| Aes256Gcm : hpke_rs_crypto.types.AeadAlgorithm
| ChaCha20Poly1305 : hpke_rs_crypto.types.AeadAlgorithm
| HpkeExport : hpke_rs_crypto.types.AeadAlgorithm

/-- [hpke_rs_crypto::types::KemAlgorithm]
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/traits/src/types.rs', lines 15:0-15:21
    Name pattern: [hpke_rs_crypto::types::KemAlgorithm]
    Visibility: public -/
@[discriminant u16 [16,17,18,22,32,33,77,25722,65,66], rust_type
  "hpke_rs_crypto::types::KemAlgorithm"]
inductive hpke_rs_crypto.types.KemAlgorithm where
| DhKemP256 : hpke_rs_crypto.types.KemAlgorithm
| DhKemP384 : hpke_rs_crypto.types.KemAlgorithm
| DhKemP521 : hpke_rs_crypto.types.KemAlgorithm
| DhKemK256 : hpke_rs_crypto.types.KemAlgorithm
| DhKem25519 : hpke_rs_crypto.types.KemAlgorithm
| DhKem448 : hpke_rs_crypto.types.KemAlgorithm
| XWingDraft06Obsolete : hpke_rs_crypto.types.KemAlgorithm
| XWingDraft06 : hpke_rs_crypto.types.KemAlgorithm
| MlKem768 : hpke_rs_crypto.types.KemAlgorithm
| MlKem1024 : hpke_rs_crypto.types.KemAlgorithm

/-- Trait declaration: [hpke_rs_crypto::HpkeTestRng]
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/traits/src/lib.rs', lines 150:0-150:21
    Name pattern: [hpke_rs_crypto::HpkeTestRng]
    Visibility: public -/
@[rust_trait "hpke_rs_crypto::HpkeTestRng"
  (parentClauses := ["corefmtDebugInst", "corefmtDisplayInst"])]
structure hpke_rs_crypto.HpkeTestRng (Self : Type) (Self_Error : Type) where
  corefmtDebugInst : core.fmt.Debug Self_Error
  corefmtDisplayInst : core.fmt.Display Self_Error
  try_fill_test_bytes : Self → Slice Std.U8 → Result ((core.result.Result
    Unit Self_Error) × Self × (Slice Std.U8))
  seed : Self → Slice Std.U8 → Result Self

/-- [hpke_rs_crypto::error::Error]
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/traits/src/error.rs', lines 10:0-10:14
    Name pattern: [hpke_rs_crypto::error::Error]
    Visibility: public -/
@[discriminant isize, rust_type "hpke_rs_crypto::error::Error"]
inductive hpke_rs_crypto.error.Error where
| HpkeInvalidOutputLength : hpke_rs_crypto.error.Error
| UnknownKdfAlgorithm : hpke_rs_crypto.error.Error
| KemInvalidSecretKey : hpke_rs_crypto.error.Error
| KemInvalidPublicKey : hpke_rs_crypto.error.Error
| KemInvalidCiphertext : hpke_rs_crypto.error.Error
| UnknownKemAlgorithm : hpke_rs_crypto.error.Error
| UnsupportedKemOperation : hpke_rs_crypto.error.Error
| UnknownAeadAlgorithm : hpke_rs_crypto.error.Error
| AeadInvalidNonce : hpke_rs_crypto.error.Error
| AeadOpenError : hpke_rs_crypto.error.Error
| AeadInvalidCiphertext : hpke_rs_crypto.error.Error
| InsufficientRandomness : hpke_rs_crypto.error.Error
| CryptoLibraryError : String → hpke_rs_crypto.error.Error

/-- Trait declaration: [hpke_rs_crypto::HpkeCrypto]
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/traits/src/lib.rs', lines 23:0-23:52
    Name pattern: [hpke_rs_crypto::HpkeCrypto]
    Visibility: public -/
@[rust_trait "hpke_rs_crypto::HpkeCrypto"
  (parentClauses := ["corefmtDebugInst", "rand_coreCryptoRngInst", "HpkeTestRngInst", "zeroizeZeroizeInst"])]
structure hpke_rs_crypto.HpkeCrypto (Self : Type) (Self_HpkePrng : Type)
  (Self_Clause3_Clause1_Clause0_Error : Type) (Self_Clause4_Error : Type) where
  corefmtDebugInst : core.fmt.Debug Self
  rand_coreCryptoRngInst : rand_core.CryptoRng Self_HpkePrng
    Self_Clause3_Clause1_Clause0_Error
  HpkeTestRngInst : hpke_rs_crypto.HpkeTestRng Self_HpkePrng Self_Clause4_Error
  zeroizeZeroizeInst : zeroize.Zeroize Self_HpkePrng
  «name» : Result String
  supports_kdf : hpke_rs_crypto.types.KdfAlgorithm → Result
    (core.result.Result Unit hpke_rs_crypto.error.Error)
  supports_kem : hpke_rs_crypto.types.KemAlgorithm → Result
    (core.result.Result Unit hpke_rs_crypto.error.Error)
  supports_aead : hpke_rs_crypto.types.AeadAlgorithm → Result
    (core.result.Result Unit hpke_rs_crypto.error.Error)
  prng : Result Self_HpkePrng
  kdf_extract : hpke_rs_crypto.types.KdfAlgorithm → Slice Std.U8 → Slice
    Std.U8 → Result (core.result.Result (alloc.vec.Vec Std.U8)
    hpke_rs_crypto.error.Error)
  kdf_expand : hpke_rs_crypto.types.KdfAlgorithm → Slice Std.U8 → Slice
    Std.U8 → Std.Usize → Result (core.result.Result (alloc.vec.Vec Std.U8)
    hpke_rs_crypto.error.Error)
  dh : hpke_rs_crypto.types.KemAlgorithm → Slice Std.U8 → Slice Std.U8 →
    Result (core.result.Result (alloc.vec.Vec Std.U8)
    hpke_rs_crypto.error.Error)
  secret_to_public : hpke_rs_crypto.types.KemAlgorithm → Slice Std.U8 →
    Result (core.result.Result (alloc.vec.Vec Std.U8)
    hpke_rs_crypto.error.Error)
  kem_key_gen : hpke_rs_crypto.types.KemAlgorithm → Self_HpkePrng → Result
    ((core.result.Result ((alloc.vec.Vec Std.U8) × (alloc.vec.Vec Std.U8))
    hpke_rs_crypto.error.Error) × Self_HpkePrng)
  kem_key_gen_derand : hpke_rs_crypto.types.KemAlgorithm → Slice Std.U8 →
    Result (core.result.Result ((alloc.vec.Vec Std.U8) × (alloc.vec.Vec
    Std.U8)) hpke_rs_crypto.error.Error)
  kem_encaps : hpke_rs_crypto.types.KemAlgorithm → Slice Std.U8 →
    Self_HpkePrng → Result ((core.result.Result ((alloc.vec.Vec Std.U8) ×
    (alloc.vec.Vec Std.U8)) hpke_rs_crypto.error.Error) × Self_HpkePrng)
  kem_decaps : hpke_rs_crypto.types.KemAlgorithm → Slice Std.U8 → Slice
    Std.U8 → Result (core.result.Result (alloc.vec.Vec Std.U8)
    hpke_rs_crypto.error.Error)
  dh_validate_sk : hpke_rs_crypto.types.KemAlgorithm → Slice Std.U8 →
    Result (core.result.Result (alloc.vec.Vec Std.U8)
    hpke_rs_crypto.error.Error)
  aead_seal : hpke_rs_crypto.types.AeadAlgorithm → Slice Std.U8 → Slice
    Std.U8 → Slice Std.U8 → Slice Std.U8 → Result (core.result.Result
    (alloc.vec.Vec Std.U8) hpke_rs_crypto.error.Error)
  aead_open : hpke_rs_crypto.types.AeadAlgorithm → Slice Std.U8 → Slice
    Std.U8 → Slice Std.U8 → Slice Std.U8 → Result (core.result.Result
    (alloc.vec.Vec Std.U8) hpke_rs_crypto.error.Error)

/-- [hpke_rs_libcrux::HpkeLibcrux]
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/libcrux_provider/src/lib.rs', lines 31:0-31:22
    Name pattern: [hpke_rs_libcrux::HpkeLibcrux]
    Visibility: public -/
@[reducible, rust_type "hpke_rs_libcrux::HpkeLibcrux"]
def hpke_rs_libcrux.HpkeLibcrux := Unit

/-- [libcrux_curve25519::Error]
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/crates/algorithms/curve25519/src/lib.rs', lines 22:0-22:16
    Name pattern: [libcrux_curve25519::Error]
    Visibility: public -/
@[reducible, rust_type "libcrux_curve25519::Error"]
def libcrux_curve25519.Error := Unit

/-- [libcrux_ecdh::hacl::p256::Error]
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/libcrux-ecdh/src/hacl/p256.rs', lines 9:0-9:14
    Name pattern: [libcrux_ecdh::hacl::p256::Error]
    Visibility: public -/
@[discriminant isize, rust_type "libcrux_ecdh::hacl::p256::Error"]
inductive libcrux_ecdh.hacl.p256.Error where
| InvalidInput : libcrux_ecdh.hacl.p256.Error
| InvalidScalar : libcrux_ecdh.hacl.p256.Error
| InvalidPoint : libcrux_ecdh.hacl.p256.Error
| NoCompressedPoint : libcrux_ecdh.hacl.p256.Error
| NoUnCompressedPoint : libcrux_ecdh.hacl.p256.Error

/-- [libcrux_ecdh::hacl::curve25519::Error]
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/libcrux-ecdh/src/hacl/curve25519.rs', lines 2:0-2:14
    Name pattern: [libcrux_ecdh::hacl::curve25519::Error]
    Visibility: public -/
@[discriminant isize, rust_type "libcrux_ecdh::hacl::curve25519::Error"]
inductive libcrux_ecdh.hacl.curve25519.Error where
| InvalidInput : libcrux_ecdh.hacl.curve25519.Error

/-- [libcrux_ecdh::hacl::Error]
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/libcrux-ecdh/src/hacl.rs', lines 16:0-16:14
    Name pattern: [libcrux_ecdh::hacl::Error]
    Visibility: public -/
@[discriminant isize, rust_type "libcrux_ecdh::hacl::Error"]
inductive libcrux_ecdh.hacl.Error where
| Curve25519 : libcrux_ecdh.hacl.curve25519.Error → libcrux_ecdh.hacl.Error
| P256 : libcrux_ecdh.hacl.p256.Error → libcrux_ecdh.hacl.Error

/-- [libcrux_ecdh::LowLevelError]
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/libcrux-ecdh/src/ecdh.rs', lines 17:0-17:22
    Name pattern: [libcrux_ecdh::LowLevelError]
    Visibility: public -/
@[discriminant isize, rust_type "libcrux_ecdh::LowLevelError"]
inductive libcrux_ecdh.LowLevelError where
| Jasmin : String → libcrux_ecdh.LowLevelError
| Hacl : libcrux_ecdh.hacl.Error → libcrux_ecdh.LowLevelError

/-- [libcrux_ecdh::Error]
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/libcrux-ecdh/src/ecdh.rs', lines 23:0-23:14
    Name pattern: [libcrux_ecdh::Error]
    Visibility: public -/
@[discriminant isize, rust_type "libcrux_ecdh::Error"]
inductive libcrux_ecdh.Error where
| InvalidPoint : libcrux_ecdh.Error
| InvalidScalar : libcrux_ecdh.Error
| UnknownAlgorithm : libcrux_ecdh.Error
| KeyGenError : libcrux_ecdh.Error
| Custom : String → libcrux_ecdh.Error
| Wrap : libcrux_ecdh.LowLevelError → libcrux_ecdh.Error

/-- [libcrux_ecdh::p256_internal::PrivateKey]
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/libcrux-ecdh/src/p256_internal.rs', lines 9:0-9:21
    Name pattern: [libcrux_ecdh::p256_internal::PrivateKey]
    Visibility: public -/
@[reducible, rust_type "libcrux_ecdh::p256_internal::PrivateKey"]
def libcrux_ecdh.p256_internal.PrivateKey := Array Std.U8 32#usize

/-- [libcrux_ecdh::p256_internal::PublicKey]
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/libcrux-ecdh/src/p256_internal.rs', lines 19:0-19:20
    Name pattern: [libcrux_ecdh::p256_internal::PublicKey]
    Visibility: public -/
@[reducible, rust_type "libcrux_ecdh::p256_internal::PublicKey"]
def libcrux_ecdh.p256_internal.PublicKey := Array Std.U8 64#usize

/-- [libcrux_ecdh::x25519::PrivateKey]
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/libcrux-ecdh/src/x25519.rs', lines 9:0-9:21
    Name pattern: [libcrux_ecdh::x25519::PrivateKey]
    Visibility: public -/
@[reducible, rust_type "libcrux_ecdh::x25519::PrivateKey"]
def libcrux_ecdh.x25519.PrivateKey := Array Std.U8 32#usize

/-- [libcrux_ecdh::x25519::PublicKey]
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/libcrux-ecdh/src/x25519.rs', lines 19:0-19:20
    Name pattern: [libcrux_ecdh::x25519::PublicKey]
    Visibility: public -/
@[reducible, rust_type "libcrux_ecdh::x25519::PublicKey"]
def libcrux_ecdh.x25519.PublicKey := Array Std.U8 32#usize

/-- [libcrux_kem::Algorithm]
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/libcrux-kem/src/kem.rs', lines 103:0-103:18
    Name pattern: [libcrux_kem::Algorithm]
    Visibility: public -/
@[discriminant isize, rust_type "libcrux_kem::Algorithm"]
inductive libcrux_kem.Algorithm where
| X25519 : libcrux_kem.Algorithm
| X448 : libcrux_kem.Algorithm
| Secp256r1 : libcrux_kem.Algorithm
| Secp384r1 : libcrux_kem.Algorithm
| Secp521r1 : libcrux_kem.Algorithm
| MlKem512 : libcrux_kem.Algorithm
| MlKem768 : libcrux_kem.Algorithm
| X25519MlKem768Draft00 : libcrux_kem.Algorithm
| XWingKemDraft06 : libcrux_kem.Algorithm
| MlKem1024 : libcrux_kem.Algorithm

/-- [libcrux_kem::Error]
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/libcrux-kem/src/kem.rs', lines 117:0-117:14
    Name pattern: [libcrux_kem::Error]
    Visibility: public -/
@[discriminant isize, rust_type "libcrux_kem::Error"]
inductive libcrux_kem.Error where
| EcDhError : libcrux_ecdh.Error → libcrux_kem.Error
| KeyGen : libcrux_kem.Error
| Encapsulate : libcrux_kem.Error
| Decapsulate : libcrux_kem.Error
| UnsupportedAlgorithm : libcrux_kem.Error
| InvalidPrivateKey : libcrux_kem.Error
| InvalidPublicKey : libcrux_kem.Error
| InvalidCiphertext : libcrux_kem.Error

/-- [libcrux_kem::X25519MlKem768Draft00PrivateKey]
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/libcrux-kem/src/kem.rs', lines 152:0-152:42
    Name pattern: [libcrux_kem::X25519MlKem768Draft00PrivateKey]
    Visibility: public -/
@[rust_type "libcrux_kem::X25519MlKem768Draft00PrivateKey"]
structure libcrux_kem.X25519MlKem768Draft00PrivateKey where
  mlkem : libcrux_ml_kem.types.MlKemPrivateKey 2400#usize
  x25519 : libcrux_ecdh.x25519.PrivateKey

/-- [libcrux_kem::XWingKemDraft06PrivateKey]
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/libcrux-kem/src/kem.rs', lines 177:0-177:36
    Name pattern: [libcrux_kem::XWingKemDraft06PrivateKey]
    Visibility: public -/
@[rust_type "libcrux_kem::XWingKemDraft06PrivateKey"]
structure libcrux_kem.XWingKemDraft06PrivateKey where
  seed : Array Std.U8 32#usize

/-- [libcrux_kem::PrivateKey]
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/libcrux-kem/src/kem.rs', lines 194:0-194:19
    Name pattern: [libcrux_kem::PrivateKey]
    Visibility: public -/
@[discriminant isize, rust_type "libcrux_kem::PrivateKey"]
inductive libcrux_kem.PrivateKey where
| X25519 : libcrux_ecdh.x25519.PrivateKey → libcrux_kem.PrivateKey
| P256 : libcrux_ecdh.p256_internal.PrivateKey → libcrux_kem.PrivateKey
| MlKem512 :
  libcrux_ml_kem.types.MlKemPrivateKey 1632#usize →
  libcrux_kem.PrivateKey
| MlKem768 :
  libcrux_ml_kem.types.MlKemPrivateKey 2400#usize →
  libcrux_kem.PrivateKey
| X25519MlKem768Draft00 :
  libcrux_kem.X25519MlKem768Draft00PrivateKey →
  libcrux_kem.PrivateKey
| XWingKemDraft06 :
  libcrux_kem.XWingKemDraft06PrivateKey →
  libcrux_kem.PrivateKey
| MlKem1024 :
  libcrux_ml_kem.types.MlKemPrivateKey 3168#usize →
  libcrux_kem.PrivateKey

/-- [libcrux_kem::X25519MlKem768Draft00PublicKey]
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/libcrux-kem/src/kem.rs', lines 206:0-206:41
    Name pattern: [libcrux_kem::X25519MlKem768Draft00PublicKey]
    Visibility: public -/
@[rust_type "libcrux_kem::X25519MlKem768Draft00PublicKey"]
structure libcrux_kem.X25519MlKem768Draft00PublicKey where
  mlkem : libcrux_ml_kem.types.MlKemPublicKey 1184#usize
  x25519 : libcrux_ecdh.x25519.PublicKey

/-- [libcrux_kem::XWingKemDraft06PublicKey]
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/libcrux-kem/src/kem.rs', lines 237:0-237:35
    Name pattern: [libcrux_kem::XWingKemDraft06PublicKey]
    Visibility: public -/
@[rust_type "libcrux_kem::XWingKemDraft06PublicKey"]
structure libcrux_kem.XWingKemDraft06PublicKey where
  pk_m : libcrux_ml_kem.types.MlKemPublicKey 1184#usize
  pk_x : libcrux_ecdh.x25519.PublicKey

/-- [libcrux_kem::PublicKey]
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/libcrux-kem/src/kem.rs', lines 269:0-269:18
    Name pattern: [libcrux_kem::PublicKey]
    Visibility: public -/
@[discriminant u8, rust_type "libcrux_kem::PublicKey"]
inductive libcrux_kem.PublicKey where
| X25519 : libcrux_ecdh.x25519.PublicKey → libcrux_kem.PublicKey
| P256 : libcrux_ecdh.p256_internal.PublicKey → libcrux_kem.PublicKey
| MlKem512 :
  libcrux_ml_kem.types.MlKemPublicKey 800#usize →
  libcrux_kem.PublicKey
| MlKem768 :
  libcrux_ml_kem.types.MlKemPublicKey 1184#usize →
  libcrux_kem.PublicKey
| X25519MlKem768Draft00 :
  libcrux_kem.X25519MlKem768Draft00PublicKey →
  libcrux_kem.PublicKey
| XWingKemDraft06 :
  libcrux_kem.XWingKemDraft06PublicKey →
  libcrux_kem.PublicKey
| MlKem1024 :
  libcrux_ml_kem.types.MlKemPublicKey 1568#usize →
  libcrux_kem.PublicKey

/-- [libcrux_traits::kem::arrayref::DecapsError]
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/traits/src/kem/arrayref.rs', lines 69:0-69:20
    Name pattern: [libcrux_traits::kem::arrayref::DecapsError]
    Visibility: public -/
@[discriminant isize, rust_type "libcrux_traits::kem::arrayref::DecapsError"]
inductive libcrux_traits.kem.arrayref.DecapsError where
| InvalidCiphertext : libcrux_traits.kem.arrayref.DecapsError
| InvalidDecapsKey : libcrux_traits.kem.arrayref.DecapsError
| Unknown : libcrux_traits.kem.arrayref.DecapsError

/-- [libcrux_traits::kem::arrayref::EncapsError]
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/traits/src/kem/arrayref.rs', lines 56:0-56:20
    Name pattern: [libcrux_traits::kem::arrayref::EncapsError]
    Visibility: public -/
@[discriminant isize, rust_type "libcrux_traits::kem::arrayref::EncapsError"]
inductive libcrux_traits.kem.arrayref.EncapsError where
| InvalidEncapsKey : libcrux_traits.kem.arrayref.EncapsError
| InvalidRandomness : libcrux_traits.kem.arrayref.EncapsError
| Unknown : libcrux_traits.kem.arrayref.EncapsError

/-- [libcrux_traits::kem::arrayref::KeyGenError]
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/traits/src/kem/arrayref.rs', lines 46:0-46:20
    Name pattern: [libcrux_traits::kem::arrayref::KeyGenError]
    Visibility: public -/
@[discriminant isize, rust_type "libcrux_traits::kem::arrayref::KeyGenError"]
inductive libcrux_traits.kem.arrayref.KeyGenError where
| InvalidRandomness : libcrux_traits.kem.arrayref.KeyGenError
| Unknown : libcrux_traits.kem.arrayref.KeyGenError

/-- Trait declaration: [libcrux_traits::kem::arrayref::Kem]
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/traits/src/kem/arrayref.rs', lines 8:0-15:1
    Name pattern: [libcrux_traits::kem::arrayref::Kem]
    Visibility: public -/
@[rust_trait "libcrux_traits::kem::arrayref::Kem"]
structure libcrux_traits.kem.arrayref.Kem (Self : Type) (EK_LEN : Std.Usize)
  (DK_LEN : Std.Usize) (CT_LEN : Std.Usize) (SS_LEN : Std.Usize)
  (RAND_KEYGEN_LEN : Std.Usize) (RAND_ENCAPS_LEN : Std.Usize) where
  keygen : Array Std.U8 EK_LEN → Array Std.U8 DK_LEN → Array Std.U8
    RAND_KEYGEN_LEN → Result ((core.result.Result Unit
    libcrux_traits.kem.arrayref.KeyGenError) × (Array Std.U8 EK_LEN) × (Array
    Std.U8 DK_LEN))
  encaps : Array Std.U8 CT_LEN → Array Std.U8 SS_LEN → Array Std.U8 EK_LEN
    → Array Std.U8 RAND_ENCAPS_LEN → Result ((core.result.Result Unit
    libcrux_traits.kem.arrayref.EncapsError) × (Array Std.U8 CT_LEN) × (Array
    Std.U8 SS_LEN))
  decaps : Array Std.U8 SS_LEN → Array Std.U8 CT_LEN → Array Std.U8 DK_LEN
    → Result ((core.result.Result Unit
    libcrux_traits.kem.arrayref.DecapsError) × (Array Std.U8 SS_LEN))

/-- [libcrux_ml_kem::mlkem768::MlKem768]
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/libcrux-ml-kem/src/mlkem768.rs', lines 37:0-37:19
    Name pattern: [libcrux_ml_kem::mlkem768::MlKem768]
    Visibility: public -/
@[reducible, rust_type "libcrux_ml_kem::mlkem768::MlKem768"]
def libcrux_ml_kem.mlkem768.MlKem768 := Unit

/-- Trait declaration: [rand_core::RngCore]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_core-0.10.1/src/lib.rs', lines 257:0-257:22
    Name pattern: [rand_core::RngCore]
    Visibility: public -/
@[rust_trait "rand_core::RngCore" (parentClauses := ["RngInst"])]
structure rand_core.RngCore (Self : Type) where
  RngInst : rand_core.Rng Self

/-- [securedrop_protocol_minimal::metadata::MetadataCiphertext]
    Source: 'protocol-minimal/src/metadata.rs', lines 90:0-95:1
    Visibility: public -/
structure metadata.MetadataCiphertext where
  c : Array Std.U8 1120#usize
  cp : Array Std.U8 1232#usize

/-- [securedrop_protocol_minimal::message::MessageCiphertext]
    Source: 'protocol-minimal/src/message.rs', lines 159:0-166:1
    Visibility: public -/
structure message.MessageCiphertext where
  c1 : Array Std.U8 32#usize
  cp : alloc.vec.Vec Std.U8
  c2 : Array Std.U8 1088#usize

/-- [securedrop_protocol_minimal::ciphertext::Envelope]
    Source: 'protocol-minimal/src/ciphertext.rs', lines 44:0-58:1
    Visibility: public -/
structure ciphertext.Envelope where
  ct_apke : message.MessageCiphertext
  ct_pke : metadata.MetadataCiphertext
  mgdh_pubkey : Array Std.U8 32#usize
  mgdh : Array Std.U8 32#usize

/-- [securedrop_protocol_minimal::ciphertext::Plaintext]
    Source: 'protocol-minimal/src/ciphertext.rs', lines 78:0-85:1
    Visibility: public -/
structure ciphertext.Plaintext where
  sender_reply_pubkey_hybrid : Array Std.U8 1216#usize
  sender_fetch_key : Array Std.U8 32#usize
  msg : alloc.vec.Vec Std.U8

/-- [securedrop_protocol_minimal::primitives::x25519::DHPrivateKey]
    Source: 'protocol-minimal/src/primitives/x25519.rs', lines 50:0-50:50
    Visibility: public -/
@[reducible]
def primitives.x25519.DHPrivateKey := Array Std.U8 32#usize

/-- [securedrop_protocol_minimal::primitives::x25519::DHPublicKey]
    Source: 'protocol-minimal/src/primitives/x25519.rs', lines 17:0-17:48
    Visibility: public -/
@[reducible]
def primitives.x25519.DHPublicKey := Array Std.U8 32#usize

/-- [securedrop_protocol_minimal::primitives::mlkem::MLKEM768PrivateKey]
    Source: 'protocol-minimal/src/primitives/mlkem.rs', lines 20:0-20:69 -/
@[reducible]
def primitives.mlkem.MLKEM768PrivateKey := Array Std.U8 2400#usize

/-- [securedrop_protocol_minimal::primitives::dh_akem::DhAkemPrivateKey]
    Source: 'protocol-minimal/src/primitives/dh_akem.rs', lines 17:0-17:66 -/
@[reducible]
def primitives.dh_akem.DhAkemPrivateKey := Array Std.U8 32#usize

/-- [securedrop_protocol_minimal::message::MessagePrivateKey]
    Source: 'protocol-minimal/src/message.rs', lines 70:0-73:1
    Visibility: public -/
structure message.MessagePrivateKey where
  dhakem : primitives.dh_akem.DhAkemPrivateKey
  mlkem : primitives.mlkem.MLKEM768PrivateKey

/-- [securedrop_protocol_minimal::primitives::mlkem::MLKEM768PublicKey]
    Source: 'protocol-minimal/src/primitives/mlkem.rs', lines 16:0-16:67 -/
@[reducible]
def primitives.mlkem.MLKEM768PublicKey := Array Std.U8 1184#usize

/-- [securedrop_protocol_minimal::primitives::dh_akem::DhAkemPublicKey]
    Source: 'protocol-minimal/src/primitives/dh_akem.rs', lines 13:0-13:64 -/
@[reducible]
def primitives.dh_akem.DhAkemPublicKey := Array Std.U8 32#usize

/-- [securedrop_protocol_minimal::message::MessagePublicKey]
    Source: 'protocol-minimal/src/message.rs', lines 60:0-63:1
    Visibility: public -/
structure message.MessagePublicKey where
  dhakem : primitives.dh_akem.DhAkemPublicKey
  mlkem : primitives.mlkem.MLKEM768PublicKey

/-- [securedrop_protocol_minimal::primitives::xwing::XWingPrivateKey]
    Source: 'protocol-minimal/src/primitives/xwing.rs', lines 16:0-16:63 -/
@[reducible]
def primitives.xwing.XWingPrivateKey := Array Std.U8 32#usize

/-- [securedrop_protocol_minimal::metadata::MetadataPrivateKey]
    Source: 'protocol-minimal/src/metadata.rs', lines 44:0-44:58
    Visibility: public -/
@[reducible]
def metadata.MetadataPrivateKey := primitives.xwing.XWingPrivateKey

/-- [securedrop_protocol_minimal::primitives::xwing::XWingPublicKey]
    Source: 'protocol-minimal/src/primitives/xwing.rs', lines 12:0-12:61 -/
@[reducible]
def primitives.xwing.XWingPublicKey := Array Std.U8 1216#usize

/-- [securedrop_protocol_minimal::metadata::MetadataPublicKey]
    Source: 'protocol-minimal/src/metadata.rs', lines 40:0-40:56
    Visibility: public -/
@[reducible]
def metadata.MetadataPublicKey := primitives.xwing.XWingPublicKey

/-- [securedrop_protocol_minimal::metadata::MetadataKeyPair]
    Source: 'protocol-minimal/src/metadata.rs', lines 48:0-51:1
    Visibility: public -/
structure metadata.MetadataKeyPair where
  sk : metadata.MetadataPrivateKey
  pk : metadata.MetadataPublicKey

/-- [securedrop_protocol_minimal::message::MessageKeyPair]
    Source: 'protocol-minimal/src/message.rs', lines 77:0-80:1
    Visibility: public -/
structure message.MessageKeyPair where
  sk : message.MessagePrivateKey
  pk : message.MessagePublicKey

/-- [securedrop_protocol_minimal::keys::MessageKeyBundle]
    Source: 'protocol-minimal/src/keys.rs', lines 61:0-64:1 -/
structure keys.MessageKeyBundle where
  apke : message.MessageKeyPair
  metadata_kp : metadata.MetadataKeyPair

/-- Trait declaration: [securedrop_protocol_minimal::traits::UserSecret]
    Source: 'protocol-minimal/src/traits.rs', lines 84:0-93:1
    Visibility: public -/
structure traits.UserSecret (Self : Type) where
  num_bundles : Self → Result Std.Usize
  fetch_keypair : Self → Result (primitives.x25519.DHPrivateKey ×
    primitives.x25519.DHPublicKey)
  message_auth_key : Self → Result message.MessagePrivateKey
  own_message_auth_pk : Self → Result message.MessagePublicKey
  build_message : Self → alloc.vec.Vec Std.U8 → Result ciphertext.Plaintext
  keybundles : Self → Result (alloc.vec.Vec keys.MessageKeyBundle)

/-- Trait declaration: [securedrop_protocol_minimal::traits::UserPublic]
    Source: 'protocol-minimal/src/traits.rs', lines 29:0-36:1
    Visibility: public -/
structure traits.UserPublic (Self : Type) where
  fetch_pk : Self → Result primitives.x25519.DHPublicKey
  message_auth_pk : Self → Result message.MessagePublicKey
  message_metadata_pk : Self → Result metadata.MetadataPublicKey
  message_enc_pk : Self → Result message.MessagePublicKey

/-- [securedrop_protocol_minimal::primitives::x25519::dh_shared_secret::closure]
    Source: 'protocol-minimal/src/primitives/x25519.rs', lines 169:17-169:56 -/
@[reducible]
def primitives.x25519.dh_shared_secret.closure := Unit

/-- [securedrop_protocol_minimal::primitives::x25519::DHSharedSecret]
    Source: 'protocol-minimal/src/primitives/x25519.rs', lines 71:0-71:36
    Visibility: public -/
@[reducible]
def primitives.x25519.DHSharedSecret := Array Std.U8 32#usize

/-- [securedrop_protocol_minimal::primitives::x25519::generate_dh_keypair::closure]
    Source: 'protocol-minimal/src/primitives/x25519.rs', lines 116:17-116:68 -/
@[reducible]
def primitives.x25519.generate_dh_keypair.closure (R : Type)
  (Clause1_Clause1_Clause0_Error : Type) :=
Unit

/-- [securedrop_protocol_minimal::message::auth_enc::closure#1]
    Source: 'protocol-minimal/src/message.rs', lines 317:17-317:71 -/
@[reducible]
def message.auth_enc.closure_1 (R : Type) (Clause1_Clause1_Clause0_Error :
  Type) :=
Unit

/-- [securedrop_protocol_minimal::message::auth_enc::closure]
    Source: 'protocol-minimal/src/message.rs', lines 297:17-297:76 -/
@[reducible]
def message.auth_enc.closure (R : Type) (Clause1_Clause1_Clause0_Error : Type)
  :=
Unit

/-- [securedrop_protocol_minimal::primitives::mlkem::generate_mlkem768_keypair::closure]
    Source: 'protocol-minimal/src/primitives/mlkem.rs', lines 122:17-122:80 -/
@[reducible]
def primitives.mlkem.generate_mlkem768_keypair.closure (R : Type)
  (Clause1_Clause1_Clause0_Error : Type) :=
Unit

/-- [securedrop_protocol_minimal::primitives::mlkem::typed::closure#1]
    Source: 'protocol-minimal/src/primitives/mlkem.rs', lines 108:21-108:78 -/
@[reducible]
def primitives.mlkem.typed.closure_1 := Unit

/-- [securedrop_protocol_minimal::primitives::mlkem::typed::closure]
    Source: 'protocol-minimal/src/primitives/mlkem.rs', lines 102:21-102:79 -/
@[reducible]
def primitives.mlkem.typed.closure := Unit

/-- [securedrop_protocol_minimal::primitives::dh_akem::generate_dh_akem_keypair::closure]
    Source: 'protocol-minimal/src/primitives/dh_akem.rs', lines 147:17-147:78 -/
@[reducible]
def primitives.dh_akem.generate_dh_akem_keypair.closure (R : Type)
  (Clause1_Clause1_Clause0_Error : Type) :=
Unit

/-- [securedrop_protocol_minimal::primitives::dh_akem::typed::closure#1]
    Source: 'protocol-minimal/src/primitives/dh_akem.rs', lines 133:21-133:78 -/
@[reducible]
def primitives.dh_akem.typed.closure_1 := Unit

/-- [securedrop_protocol_minimal::primitives::dh_akem::typed::closure]
    Source: 'protocol-minimal/src/primitives/dh_akem.rs', lines 127:21-127:79 -/
@[reducible]
def primitives.dh_akem.typed.closure := Unit

/-- [securedrop_protocol_minimal::primitives::mlkem::deterministic_keygen::closure]
    Source: 'protocol-minimal/src/primitives/mlkem.rs', lines 62:17-62:94 -/
@[reducible]
def primitives.mlkem.deterministic_keygen.closure := Unit

/-- [securedrop_protocol_minimal::primitives::dh_akem::deterministic_keygen::closure]
    Source: 'protocol-minimal/src/primitives/dh_akem.rs', lines 75:17-75:92 -/
@[reducible]
def primitives.dh_akem.deterministic_keygen.closure := Unit

/-- [securedrop_protocol_minimal::message::auth_dec::closure#1]
    Source: 'protocol-minimal/src/message.rs', lines 376:13-376:67 -/
@[reducible]
def message.auth_dec.closure_1 := Unit

/-- [securedrop_protocol_minimal::message::auth_dec::closure]
    Source: 'protocol-minimal/src/message.rs', lines 356:17-356:76 -/
@[reducible]
def message.auth_dec.closure := Unit

/-- [securedrop_protocol_minimal::primitives::xwing::generate_xwing_keypair::closure]
    Source: 'protocol-minimal/src/primitives/xwing.rs', lines 123:17-123:76 -/
@[reducible]
def primitives.xwing.generate_xwing_keypair.closure (R : Type)
  (Clause1_Clause1_Clause0_Error : Type) :=
Unit

/-- [securedrop_protocol_minimal::primitives::xwing::typed::closure#1]
    Source: 'protocol-minimal/src/primitives/xwing.rs', lines 109:21-109:78 -/
@[reducible]
def primitives.xwing.typed.closure_1 := Unit

/-- [securedrop_protocol_minimal::primitives::xwing::typed::closure]
    Source: 'protocol-minimal/src/primitives/xwing.rs', lines 103:21-103:79 -/
@[reducible]
def primitives.xwing.typed.closure := Unit

/-- [securedrop_protocol_minimal::primitives::xwing::deterministic_keygen::closure]
    Source: 'protocol-minimal/src/primitives/xwing.rs', lines 63:17-63:90 -/
@[reducible]
def primitives.xwing.deterministic_keygen.closure := Unit

/-- [securedrop_protocol_minimal::metadata::{securedrop_protocol_minimal::metadata::MetadataPublicKey}::from_bytes::closure]
    Source: 'protocol-minimal/src/metadata.rs', lines 196:71-202:9 -/
@[reducible]
def metadata.MetadataPublicKey.from_bytes.closure := Slice Std.U8

/-- [securedrop_protocol_minimal::metadata::decrypt::closure]
    Source: 'protocol-minimal/src/metadata.rs', lines 286:17-286:73 -/
@[reducible]
def metadata.decrypt.closure := Unit

/-- Trait declaration: [securedrop_protocol_minimal::sign::DomainTag]
    Source: 'protocol-minimal/src/sign.rs', lines 29:0-32:1
    Visibility: public -/
structure sign.DomainTag (Self : Type) where
  tag : Result (Slice Std.U8)

/-- [securedrop_protocol_minimal::sign::JournalistLongTermKey]
    Source: 'protocol-minimal/src/sign.rs', lines 36:0-36:33
    Visibility: public -/
@[reducible]
def sign.JournalistLongTermKey := Unit

/-- [securedrop_protocol_minimal::sign::JournalistEphemeralKey]
    Source: 'protocol-minimal/src/sign.rs', lines 40:0-40:34
    Visibility: public -/
@[reducible]
def sign.JournalistEphemeralKey := Unit

/-- [securedrop_protocol_minimal::sign::NewsroomOnJournalist]
    Source: 'protocol-minimal/src/sign.rs', lines 44:0-44:32
    Visibility: public -/
@[reducible]
def sign.NewsroomOnJournalist := Unit

/-- [securedrop_protocol_minimal::sign::FpfOnNewsroom]
    Source: 'protocol-minimal/src/sign.rs', lines 48:0-48:25
    Visibility: public -/
@[reducible]
def sign.FpfOnNewsroom := Unit

/-- [securedrop_protocol_minimal::sign::Signature]
    Source: 'protocol-minimal/src/sign.rs', lines 94:0-99:1
    Visibility: public -/
structure sign.Signature (D : Type) where
  bytes : Array Std.U8 64#usize
  _phantom : core.marker.PhantomData D

/-- [securedrop_protocol_minimal::sign::VerifyingKey]
    Source: 'protocol-minimal/src/sign.rs', lines 185:0-185:47
    Visibility: public -/
@[reducible]
def sign.VerifyingKey := Array Std.U8 32#usize

/-- [securedrop_protocol_minimal::sign::SigningSecretKey]
    Source: 'protocol-minimal/src/sign.rs', lines 189:0-189:58 -/
@[reducible]
def sign.SigningSecretKey := Array Std.U8 32#usize

/-- [securedrop_protocol_minimal::sign::SigningKey]
    Source: 'protocol-minimal/src/sign.rs', lines 214:0-217:1
    Visibility: public -/
structure sign.SigningKey where
  vk : sign.VerifyingKey
  sk : sign.SigningSecretKey

/-- [securedrop_protocol_minimal::sign::{securedrop_protocol_minimal::sign::VerifyingKey}::verify::closure]
    Source: 'protocol-minimal/src/sign.rs', lines 298:21-298:73 -/
@[reducible]
def sign.VerifyingKey.verify.closure (D : Type) := Unit

end securedrop_protocol_minimal
