-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [securedrop_protocol_minimal]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/-- [anyhow::Error]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anyhow-1.0.103/src/lib.rs', lines 390:0-390:16
    Name pattern: [anyhow::Error]
    Visibility: public -/
@[rust_type "anyhow::Error"]
axiom anyhow.Error : Type

/-- [hpke_rs::HpkePublicKey]
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/src/lib.rs', lines 214:0-214:24
    Name pattern: [hpke_rs::HpkePublicKey]
    Visibility: public -/
@[rust_type "hpke_rs::HpkePublicKey"]
axiom hpke_rs.HpkePublicKey : Type

/-- [hpke_rs::HpkePrivateKey]
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/src/lib.rs', lines 231:0-231:25
    Name pattern: [hpke_rs::HpkePrivateKey]
    Visibility: public -/
@[rust_type "hpke_rs::HpkePrivateKey"]
axiom hpke_rs.HpkePrivateKey : Type

/-- [hpke_rs::Hpke]
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/src/lib.rs', lines 460:0-460:45
    Name pattern: [hpke_rs::Hpke]
    Visibility: public -/
@[rust_type "hpke_rs::Hpke"]
axiom hpke_rs.Hpke (Crypto : Type) (Clause0_HpkePrng : Type)
  (Clause0_Clause3_Clause1_Clause0_Error : Type) (Clause0_Clause4_Error : Type)
  : Type

/-- [hpke_rs_libcrux::HpkeLibcruxPrng]
    Source: '/cargo/git/checkouts/hpke-rs-96cbacf2e1039d85/634caf8/libcrux_provider/src/lib.rs', lines 34:0-34:26
    Name pattern: [hpke_rs_libcrux::HpkeLibcruxPrng]
    Visibility: public -/
@[rust_type "hpke_rs_libcrux::HpkeLibcruxPrng"]
axiom hpke_rs_libcrux.HpkeLibcruxPrng : Type

/-- [libcrux_ml_kem::types::MlKemPrivateKey]
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/libcrux-ml-kem/src/types.rs', lines 5:8-7:9
    Name pattern: [libcrux_ml_kem::types::MlKemPrivateKey]
    Visibility: public -/
@[rust_type "libcrux_ml_kem::types::MlKemPrivateKey"]
axiom libcrux_ml_kem.types.MlKemPrivateKey (SIZE : Std.Usize) : Type

/-- [libcrux_ml_kem::types::MlKemPublicKey]
    Source: '/cargo/git/checkouts/libcrux-b8e0ded9ad9366a7/3cd1843/libcrux-ml-kem/src/types.rs', lines 5:8-7:9
    Name pattern: [libcrux_ml_kem::types::MlKemPublicKey]
    Visibility: public -/
@[rust_type "libcrux_ml_kem::types::MlKemPublicKey"]
axiom libcrux_ml_kem.types.MlKemPublicKey (SIZE : Std.Usize) : Type

